generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Thematique
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          thematique
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        description:
          label: Description
      list:
        title:   Thématiques
        display: [=nom, description]
      filter:  ~
      form:    ~
      edit:
        title: Modification de <em>"%%nom%%"</em>
      new:
        title: Création d'une nouvelle thématique
