regroupement_regroupement:
  class: sfDoctrineRouteCollection
  options:
    model:                Regroupement
    module:               regroupement
    prefix_path:          /regroupement
    column:               id
    with_wildcard_routes: true

referentiel_referentiel:
  class: sfDoctrineRouteCollection
  options:
    model:                Referentiel
    module:               referentiel
    prefix_path:          /referentiel
    column:               id
    with_wildcard_routes: true

regroupement:
  class: sfDoctrineRouteCollection
  options:
    model:                Regroupement
    module:               Regroupement
    prefix_path:          /Regroupement
    column:               id
    with_wildcard_routes: true

referentiel:
  class: sfDoctrineRouteCollection
  options:
    model:                Referentiel
    module:               Referentiel
    prefix_path:          /Referentiel
    column:               id
    with_wildcard_routes: true

thematique:
  class: sfDoctrineRouteCollection
  options:
    model:                Thematique
    module:               thematique
    prefix_path:          /thematique
    column:               id
    with_wildcard_routes: true

test:
  class: sfDoctrineRouteCollection
  options:
    model:                Test
    module:               test
    prefix_path:          /test
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: thematique, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
