<?php

/**
 * Assoc_WebPage_TestConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Assoc_WebPage_TestConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Assoc_WebPage_TestConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Assoc_WebPage_TestConfig');
    }
}