<?php

/**
 * ProfilTestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfilTestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfilTestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfilTest');
    }
}