<?php

/**
 * Referentiel
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Kcatoes
 * @subpackage model
 * @author     Adrien Couet <adrien.couet@keyconsulting.fr>
 */
class Referentiel extends BaseReferentiel
{

  /**
   * (non-PHPdoc)
   * @see record/sfDoctrineRecord::__toString()
   */
  public function __toString()
  {
    return (string) $this->getNom();
  }

  /**
   * Méthode de rendu pour label de formulaire
   */
  public function getLongName()
  {
    return (string) $this->getNom().', '.$this->getUrl();
  }

}