<?php

/**
 * Referentiel
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Kcatoes
 * @subpackage model
 * @author     Adrien Couet <adrien.couet@keyconsulting.fr>
 */
class Referentiel extends BaseReferentiel
{

}