<?php

/**
 * ReferentielTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReferentielTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReferentielTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Referentiel');
    }
}