<?php

/**
 * RegroupementTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 * @package    Kcatoes
 * @subpackage table
 * @author     Adrien Couet <adrien.couet@keyconsulting.fr>
 */
class RegroupementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegroupementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Regroupement');
    }
}