<?php

/**
 * Regroupement
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Kcatoes
 * @subpackage model
 * @author     Adrien Couet <adrien.couet@keyconsulting.fr>
 */
class Regroupement extends BaseRegroupement
{

}