<?php

/**
 * Regroupement
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    kcatoes
 * @subpackage model
 * @author     Adrien Couet
 */
class Regroupement extends BaseRegroupement
{

}