<?php

/**
 * ScenarioTemplatePageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScenarioTemplatePageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScenarioTemplatePageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScenarioTemplatePage');
    }
}