<?php

/**
 * ScenarioTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScenarioTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScenarioTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScenarioTemplate');
    }
}