<?php

/**
 * ScenarioPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScenarioPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScenarioPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScenarioPage');
    }
}