<?php

/**
 * ScenarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScenarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScenarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Scenario');
    }
}