<?php

/**
 * TestConfigDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TestConfigDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TestConfigDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TestConfigDetail');
    }
}