<?php

/**
 * TestResultLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TestResultLineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TestResultLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TestResultLine');
    }
}