<?php

/**
 * TestConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TestConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TestConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TestConfig');
    }
}