<?php

/**
 * Thematique
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Kcatoes
 * @subpackage model
 * @author     Adrien Couet <adrien.couet@keyconsulting.fr>
 */
class Thematique extends BaseThematique
{

  /**
   * (non-PHPdoc)
   * @see record/sfDoctrineRecord::__toString()
   */
  public function __toString()
  {
    return (string) $this->getNom();
  }

}