<?php

/**
 * ThematiqueTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 * @package    Kcatoes
 * @subpackage table
 * @author     Adrien Couet <adrien.couet@keyconsulting.fr>
 */
class ThematiqueTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ThematiqueTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Thematique');
  }

  public function findData()
  {
    return $this->createQuery('t')->select('nom')->execute();
  }
}