<?php

/**
 * UserTestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserTest');
    }
}