<?php

/**
 * WebPageExtractTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebPageExtractTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebPageExtractTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebPageExtract');
    }
}