<?php

/**
 * WebPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebPage');
    }
}