<?php

/**
 * WebPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebPage');
    }
    
    public static function getListUrl($withEmpty = true)
    {
      $q = Doctrine_Query::create()
       ->select('p.url, p.description')
	     ->from('WebPage p')
	     ->orderBy('p.url ASC');
      $res =  $q->fetchArray();
      
      $array = array();
      if ($withEmpty)
      {
      	$array[null] = null;
      }
      foreach($res as $line){
      	$label = $line['url'];
      	if ($line['description'])
      	{
      		$label .= ' &ndash; '.$line['description'];
      	}
      	$array[$line['id']] = $label;
      }
      return $array;
    }
}