<?php

/**
 * WebPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kcatoes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class WebPage extends BaseWebPage
{

  /**
   * Indique si un test est lié à la page
   * @param string $class La classe du test
   * @return boolean
   */
  public function hasTest($class)
  {
    $found = false;
    $pageTests = $this->getCollectionTests();
    foreach($pageTests as $test)
    {
      if ($test->getClass() == $class) {
        return true;
      }
    }
    return false;
  }
  
  /**
   * Récupère l'extraction de base
   * $return WebPageExtract
   */
  public function getBaseExtract()
  {
  	$extracts = $this->getCollectionExtracts();
  	foreach ($extracts as $extract)
  	{
  		if ($extract->getType() == 'base')
  		{
  			return $extract;
  		}
  	}
  	return false;
  }
  
  /**
   * Récupère l'extraction de base
   * $return WebPageExtract
   */
  public function getNoJsExtract()
  {
    $extracts = $this->getCollectionExtracts();
    foreach ($extracts as $extract)
    {
      if ($extract->getType() == 'Sans JavaScript')
      {
        return $extract;
      }
    }
    return false;
  }
  
  /**
   * Récupère l'extraction de base
   * $return WebPageExtract
   */
  public function getJsExtract()
  {
    $extracts = $this->getCollectionExtracts();
    foreach ($extracts as $extract)
    {
      if ($extract->getType() == 'Avec JavaScript')
      {
        return $extract;
      }
    }
    return false;
  }
  
}