all:
  version: 1.0.1
  versions_compatibles: 0.3.0
  date: 15/06/2012

  pluginpath: '<?php echo sfConfig::get('sf_lib_dir').DIRECTORY_SEPARATOR.'kcatoesPlugins' ?>'
  outputpath: '<?php echo sfConfig::get('sf_web_dir').DIRECTORY_SEPARATOR.'output' ?>'

  flagfilepath: '<?php echo sfConfig::get('sf_web_dir').DIRECTORY_SEPARATOR.'runningTests' ?>'
