# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url:   /
  param: { module: scenario, action: index }

# ################
# AUTHENTIFICATION
# ################

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# ##########################
# ADMINISTRATION UTILISATEUR
# ##########################
connexion:
  url: /connexion
  param: { module: sfGuardAuth, action: signin}

sf_guard_user:
  url: /administration/utilisateurs
  param: {module: sfGuardUser, action: index}

sf_guard_group:
  url: /administration/profils
  param: {module: sfGuardGroup, action: index}

sf_guard_group_assoc_test:
  url: /administration/profils/tests/:id
  param: {module: sfGuardGroup, action: assocTest}
  class:    sfDoctrineRoute
  options:  { model: sfGuardGroup, type: object }
  requirements: 
    id:     \d+
    sf_method: [GET, POST]

sf_guard_permission:
  url: /administration/roles
  param: {module: sfGuardPermission, action: index }
  
userTest:
  url: /mon-profil/tests/
  param: {module: sfGuardUser, action: userTest }

# ######### 
# PAGES WEB
# #########
pageIndex:
  url:      /pages
  param:    { module: page, action: index }

pageDetail:
  url:      /page/:id
  param:    { module: page, action: detail }
  class:    sfDoctrineRoute
  options:  { model: WebPage, type: object }
  requirements: 
    id:     \d+

pageEdit:
  url:      /page/:id/modifier
  param:    { module: page, action: edit }
  class:    sfDoctrineRoute
  options:  { model: WebPage, type: object }
  requirements: 
    id:     \d+
    sf_method: [GET, POST]

pageDelete:
  url:      /page/:id/supprimer
  param:    { module: page, action: delete }
  class:    sfDoctrineRoute
  options:  { model: WebPage, type: object }
  requirements: 
    id:     \d+

pageConfigurationTests:
  url:      /page/:id/configuration-tests
  param:    { module: page, action: configurationTests }
  class:    sfDoctrineRoute
  options:  { model: WebPage, type: object }
  requirements: 
    id:     \d+
    sf_method: [GET, POST]

pageExtracts:
  url: /page/:id/assistant-extraction
  param:    { module: page, action: extractWizard }
  class:    sfDoctrineRoute
  options:  { model: WebPage, type: object }
  requirements: 
    id:     \d+
    sf_method: [GET, POST]

pageExtractSrc:
  url: page/assistant-extraction/source/:id
  param:    { module: page, action: extractSrc }
  class:    sfDoctrineRoute
  options:  { model: WebPageExtract, type: object }
  requirements:
    id: \d+
    sf_method: [GET]
    
pageExecutionTests:
  url:      /page/execute-tests/:id
  param:    { module: page, action: executionTests }
  class:    sfDoctrineRoute
  options:  { model: WebPageExtract, type: object }
  requirements: 
    id:     \d+

pageSource:
  url:      /page/source/:id
  param:    { module: page, action: source }
  class:    sfDoctrineRoute
  options:  { model: WebPageExtract, type: object }
  requirements: 
    id:     \d+

# ##########
# EVALUATION
# ##########

evaluation:
  url:      /evaluation/:id
  param:    { module: eval, action: evaluation }
  class:    sfDoctrineRoute
  options:  { model: WebPageExtract, type: object }
  requirements: 
    id:     \d+
    
evaluationSauvegarde:
  url:      /evaluation/:id/save
  param:    { module: eval, action: evaluationSauvegarde }
  class:    sfDoctrineRoute
  options:  { model: WebPageExtract, type: object }
  requirements: 
    id:     \d+
    sf_method: [POST]
    
evaluationSimple:
  url:      /evaluation/:id/simple
  param:    { module: eval, action: evaluationSimple }
  class:    sfDoctrineRoute
  options:  { model: WebPageExtract, type: object }
  requirements: 
    id:     \d+

# ########
# SCENARIO
# ########
scenarioIndex:
  url:      /scenarios
  param:    { module: scenario, action: index }

scenarioTemplateIndex:
  url:      /modeles-de-scenarios
  param:    { module: scenario, action: templateIndex }

scenarioTemplateDelete:
  url:      /modele-de-scenario/:id/supprimer
  param:    { module: scenario, action: templateDelete }
  class:    sfDoctrineRoute
  options:  { model: ScenarioTemplate, type: object }
  requirements: 
    id:     \d+

scenarioDetail:
  url:      /scenario/:id
  param:    { module: scenario, action: detail }
  class:    sfDoctrineRoute
  options:  { model: Scenario, type: object }
  requirements: 
    id:     \d+
    sf_method: [GET, POST]

scenarioAvancement:
  url:      /scenario/:id/avancement
  param:    { module: scenario, action: avancement }
  class:    sfDoctrineRoute
  options:  { model: Scenario, type: object }
  requirements: 
    id:     \d+
    sf_method: [GET]

scenarioEdit:
  url:      /scenario/:id/modifier
  param:    { module: scenario, action: edit }
  class:    sfDoctrineRoute
  options:  { model: Scenario, type: object }
  requirements: 
    id:     \d+
    sf_method: [GET, POST]

scenarioDelete:
  url:      /scenario/:id/supprimer
  param:    { module: scenario, action: delete }
  class:    sfDoctrineRoute
  options:  { model: Scenario, type: object }
  requirements: 
    id:     \d+

scenarioActions:
  url:      /scenario/:id/action
  param:    { module: scenario, action: actions }
  class:    sfDoctrineRoute
  options:  { model: Scenario, type: object }
  requirements: 
    id:     \d+
    sf_method: [POST]

scenarioPageEdit:
  url:      /scenario/modifier-page/:id
  param:    { module: scenario, action: pageEdit }
  class:    sfDoctrineRoute
  options:  { model: ScenarioPage, type: object }
  requirements: 
    id:     \d+
    sf_method: [GET, POST]

scenarioPageDelete:
  url:      /scenario/supprimer-page/:id
  param:    { module: scenario, action: pageDelete }
  class:    sfDoctrineRoute
  options:  { model: ScenarioPage, type: object }
  requirements: 
    id:     \d+

# ######################
# RESULTATS (Génériques)
# ######################

resultatScenario:
  url:      /rapport/scenario/:id/:mode
  param:    { module: rapport, action: rapportScenario }
  class:    sfDoctrineRoute
  options:  { model: Scenario, type: object }
  requirements:
    id:     \d+
    mode:   \w+
    sf_method: [GET, POST]

resultatScenarioPage:
  url:      /rapport/scenario/:id/:mode/page/:idPage/extractions/:extractIds
  param:    { module: rapport, action: rapportScenarioPage }
  class:    sfDoctrineRoute
  options:  { model: Scenario, type: object }
  requirements:
    id:     \d+
    idPage:     \d+
    mode:   \w+
    sf_method: [GET, POST]

# #################
# PAGES EDITORIALES
# #################
editorial:
  url: /documentation
  param: { module: editorial, action: index }
overview:
  url: /vue-d-ensemble
  param: { module: editorial, action: overview }

aide:
  url:  /aide
  param: { module: editorial, action: aide }

credits:
  url: /credits
  param: {module: editorial, action: credits}

environnementR:
  url: /environnement-recommande
  param: {module: editorial, action: environnementR}

about:
  url: /a-propos
  param: {module: editorial, action: about}
    
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*


