<?php

/**
 * sfGuardGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kcatoes
 * @subpackage model
 * @author     Key Consulting
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardGroup extends PluginsfGuardGroup
{
  /**
   * Indique si un test est lié à la page
   * @param string $class La classe du test
   * @return boolean
   */
  public function hasTest($class)
  {
    $found = false;
    $pageTests = $this->getCollectionTests();
    foreach($pageTests as $test)
    {
      if ($test->getClass() == $class) {
        return true;
      }
    }
    return false;
  }
}
