generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Referentiel
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          referentiel_referentiel
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        thematique:
          label: Thématique
        url:
          label: URL
      list:
        title:   Référentiels
        display: [=nom, url, thematique]
      filter:  ~
      form:    ~
      edit:
        title: Modification de <em>"%%nom%%"</em>
      new:
        title: Création d'un nouveau référentiel
