# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

dev:
  doctrine:
    param:
#     dsn:      mysql:host=localhost;dbname=kcatoes_dev
      dsn:      pgsql:host=localhost;dbname=kcatoes_dev
      username: kcatoes
      password: kcatoes
       
prod:
  doctrine:
    param:
      dsn:      mysql:host=localhost;dbname=kcatoes
#     dsn:      pgsql:host=localhost;dbname=kcatoes
      username: kcatoes
      password: kcatoes

test:
  doctrine:
    param:
      dsn:      mysql:host=localhost;dbname=kcatoes_test
      username: kcatoes
      password: kcatoes 

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      persistent: true
      pooling: true
      encoding: utf8
      attributes:
        use_dql_callbacks: true
        use_native_enum: true
