generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Regroupement
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          regroupement_regroupement
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        referentiel:
          label: Référentiel
      list:
        title:   Regroupements
        display: [=nom, referentiel]
      filter:  ~
      form:    ~
      edit:
        title: Modification de <em>"%%nom%%"</em>
      new:
        title: Création d'un nouveau regroupement
