#
# Options de Doctrine
# 
# @date 23/12/2008
# @author Antoine Rolland
# 
detect_relations: false
options: 
  charset: utf8
  collate: utf8_unicode_ci
attributes: 
  export: all
  validate: true 

#
# =Thematique
# =thematique
#
# Une thématique est un thème sur lequel porte un ensemble de tests
#
# @date 23/02/2011
# @author Adrien Couet
#
Thematique:
  tableName: thematique
  columns:
    id:          { type: integer, primary: true, autoincrement: true }
    nom:         { type: string(255), notnull: true }
    description: { type: string(1024), notnull: true }

#
# =Referentiel
# =referentiel
#
# Un référentiel permet de classer les tests d'une thématique 
# en fonction du document de référence qui a permit de les écrire
#
# @date 23/02/2011
# @author Adrien Couet
#
Referentiel:
  tableName: referentiel
  columns:
    id:            { type: integer, primary: true, autoincrement: true }
    nom:           { type: string(255), notnull: true }
    url:           { type: string(255), notnull: true }
    thematique_id: { type: integer, notnull: true }
  relations:
    Thematique:
      local:        thematique_id
      foreign:      id
      foreignAlias: CollectionReferentiels

#
# =Regroupement
# =regroupement
#
# Un regroupement de contact permet d'affiner
# le classement d'un référentiel
#
# @date 23/02/2011
# @author Adrien Couet
#
Regroupement:
  tableName: regroupement
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    nom:            { type: string(255), notnull: true }
    referentiel_id: { type: integer, notnull: true }
  relations:
    Referentiel:
      local:        referentiel_id
      foreign:      id
      foreignAlias: CollectionRegroupements
      
#
# =Test
# =test
#
# Décrit un test
#
# @date 23/02/2011
# @author Adrien Couet
#
Test:
  tableName: test
  columns:
    id:              { type: integer, primary: true, autoincrement: true }
    nom:             { type: string(255), notnull: true, unique: true }
    description:     { type: string(1024), notnull: true }
    automatisable:   { type: boolean, notnull: true }
    instruction:     { type: string(1024), notnull: true }
    regroupement_id: { type: integer, notnull: true }
  relations:
    Regroupement:
      local:        regroupement_id
      foreign:      id
      foreignAlias: CollectionTests
