#
# Options de Doctrine
# 
# @date 27/01/2012
# @author Cyril FABBY
# 
detect_relations: false
options: 
  charset: utf8
  collate: utf8_unicode_ci
attributes: 
  export: all
  validate: true 

# =WebPage
# une page est défini par son url et eventuellement une description
WebPage:
  tableName: web_page
  actAs:
    - Timestampable
  columns:
    id:          { type: integer, primary: true, autoincrement: true }
    url:         { type: varchar(5000), notnull: true }
    description: { type: varchar(5000), notnull: false }
  relations: 
    CollectionTestConfig: 
      class:        TestConfig
      foreignAlias: CollectionWebPages
      refClass:     Assoc_WebPage_TestConfig

# =Evaluation
# une évaluation 
Evaluation:
  tableName: evaluation
  actAs:
    - Timestampable
  columns:
    id:          { type: integer, primary: true, autoincrement: true }
    web_page_id: { type: integer, notnull: true }
    config_id:   { type: integer, notnull: true }
  relations:
    WebPage:
      local:        web_page_id
      foreign:      id
      foreignAlias: CollectionEvals


# =TestConfig
# une configuration
TestConfig:
  tableName: test_config
  actAs:
    - Timestampable
  columns:
    id:          { type: integer, primary: true, autoincrement: true }
    libelle:     { type: varchar(255), unique: true }
    description: { type: varchar(5000) }
  relations: 
    CollectionWebPage: 
      class:        WebPage
      foreignAlias: CollectionTestConfigs
      refClass:     Assoc_WebPage_TestConfig
    
# =TestConfigDetail
# les différents tests d'une conf 
TestConfigDetail:
  tableName: test_config_detail
  actAs:
    - Timestampable
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    test_config_id: { type: integer, notnull: true }
    class:          { type: varchar(500) }
  relations:
    TestConfig:
      local:        test_config_id
      foreign:      id
      foreignAlias: CollectionTests
      
# Association WebPage TestConfig (many to many)
Assoc_WebPage_TestConfig:
  tableName: assoc_web_page_test_config
  actAs:
    - Timestampable
  columns:
    #id:             { type: integer, primary: true, autoincrement: true }
    web_page_id:    { type: integer, primary: true }
    test_config_id: { type: integer, primary: true }
  relations: 
    WebPage: 
      local: web_page_id
      foreignAlias: Associations_WebPage_TestConfig
    Fiche: 
      TestConfig: test_config_id
      foreignAlias: Associations_WebPage_TestConfig
      
    